require:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/rake
    - gemfiles/**/*
  NewCops: enable
  TargetRubyVersion: 3.2

RSpec/SpecFilePathFormat:
  CustomTransform:
    OmniAuth: omniauth

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
